<a href="https://colab.research.google.com/github/tarannump096-cpu/Deep-Learning/blob/main/Deep_Learning9.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
from abc import ABC,abstractmethod

In [ ]:
class Layers(ABC):
    @abstractmethod
    def forward_propogation(self,inputs):
        pass

In [ ]:
class Neural_Network(Layers):
    def __init__(self,inputs,neurons):
        self.weights=np.random.randn(inputs,neurons)
        self.bias=np.ones(neurons)
    def forward_propogation(self,inputs):
        self.outputs=np.dot(inputs,self.weights)+self.bias

In [ ]:
class ReLu(Layers):
    def forward_propogation(self,inputs):
        self.output=np.maximum(0,inputs)

In [ ]:
class sigmoid(Layers):
    def forward_propogation(self,inputs):
        self.output=1/(1+np.exp(-inputs))

In [ ]:
import sys
!{sys.executable} -m pip install nnfs
import nnfs

In [ ]:
from nnfs.datasets import spiral_data

In [ ]:
nnfs.init()

In [ ]:
x,y=spiral_data(samples=100,classes=2)

In [ ]:
layer1= Neural_Network(2,3)

In [ ]:
layer1.forward_propogation(x)

In [ ]:
o1=layer1.outputs

In [ ]:
af1=ReLu()

In [ ]:
af1.forward_propogation(o1)

In [ ]:
o2=af1.output

In [ ]:
o2

array([[1.00000000e+00, 1.00000000e+00, 1.00000000e+00],
       [1.00521517e+00, 1.00545802e+00, 9.87695953e-01],
       [1.00544235e+00, 1.00687883e+00, 9.89000241e-01],
       [9.91848527e-01, 9.95672026e-01, 1.02576969e+00],
       [9.91599039e-01, 9.96560744e-01, 1.02814690e+00],
       [1.03278368e+00, 1.03212712e+00, 9.19257984e-01],
       [9.98933990e-01, 1.00544493e+00, 1.01272026e+00],
       [1.02199107e+00, 1.02654487e+00, 9.53607500e-01],
       [1.01803291e+00, 1.02434291e+00, 9.65964478e-01],
       [9.96127082e-01, 1.00611319e+00, 1.02495163e+00],
       [9.98146003e-01, 1.00900522e+00, 1.02140032e+00],
       [9.41197116e-01, 9.55551218e-01, 1.16532046e+00],
       [9.53526542e-01, 9.69296508e-01, 1.13754117e+00],
       [9.69284430e-01, 9.85611535e-01, 1.10008908e+00],
       [9.41859178e-01, 9.60315604e-01, 1.17009182e+00],
       [9.33392085e-01, 9.53192115e-01, 1.19277143e+00],
       [8.82700279e-01, 8.99171196e-01, 1.31086111e+00],
       [9.31739546e-01, 9.54121

In [ ]:
layer2=Neural_Network(o2.shape[1],3)

In [ ]:
layer2.forward_propogation(o2)

In [ ]:
o3=layer2.outputs

In [ ]:
af2=ReLu()

In [ ]:
af2.forward_propogation(o3)

In [ ]:
o4=af2.output

In [ ]:
layer3=Neural_Network(o4.shape[1],2)

In [ ]:
layer3.forward_propogation(o4)

In [ ]:
o5=layer3.outputs

In [ ]:
af3=sigmoid()

In [ ]:
af3.forward_propogation(o5)

In [ ]:
o6=af3.output

In [ ]:
o6

array([[0.6359284 , 0.87459344],
       [0.63736566, 0.874759  ],
       [0.63733454, 0.87496038],
       [0.6333427 , 0.87502499],
       [0.63318218, 0.87520549],
       [0.64509341, 0.87527419],
       [0.63511355, 0.87563461],
       [0.64169425, 0.87586678],
       [0.64045622, 0.87605831],
       [0.63405163, 0.87613392],
       [0.63454764, 0.87632401],
       [0.61817849, 0.87553313],
       [0.62157161, 0.8760588 ],
       [0.62599146, 0.87652479],
       [0.61803539, 0.87621758],
       [0.61551037, 0.87623421],
       [0.60120173, 0.87447404],
       [0.61482865, 0.87661406],
       [0.60321511, 0.87571856],
       [0.61679266, 0.87715225],
       [0.64773168, 0.87822798],
       [0.58937342, 0.87410941],
       [0.58670848, 0.87326868],
       [0.59464036, 0.87611807],
       [0.60574606, 0.87036139],
       [0.59672183, 0.87687973],
       [0.57751788, 0.87305077],
       [0.57516601, 0.87306486],
       [0.60250958, 0.86958538],
       [0.60521221, 0.86930344],
       [0.

In [ ]:
class categorical_cross_entropy_loss:
    def forward(self, y_pred, y_true):

        # Prevent log(0)
        y_pred = np.clip(y_pred, 1e-7, 1 - 1e-7)

        samples = len(y_pred)

        # If labels are one-hot encoded
        if len(y_true.shape) == 2:
            y_true = np.argmax(y_true, axis=1)

        correct_confidence = y_pred[
            range(samples),
            y_true
        ]

        negative_log_likelihood = -np.log(correct_confidence)

        return np.mean(negative_log_likelihood)


# ---------------- SAMPLE DATA ---------------- #

X = np.array([
    [1, 2, 3, 2],
    [2, 3, 4, 1],
    [3, 4, 5, 2]
])

y_true = np.array([0, 1, 1])


# ---------------- NETWORK FLOW ---------------- #

# Input Layer → Hidden Layer
dense1 = Neural_Network(4, 5)
dense1.forward_propogation(X)

print("Dense Layer Output:\n")
print(dense1.outputs)


# ReLU Activation
activation1 = ReLu()
activation1.forward_propogation(dense1.outputs)

print("\nReLU Output:\n")
print(activation1.output)


# Output Layer
dense2 = Neural_Network(5, 2)
dense2.forward_propogation(activation1.output)

print("\nSecond Dense Layer Output:\n")
print(dense2.outputs)


# Sigmoid Activation
activation2 = sigmoid()
activation2.forward_propogation(dense2.outputs)

print("\nSigmoid Output:\n")
print(activation2.output)


# Loss Calculation
loss_function = categorical_cross_entropy_loss()

loss = loss_function.forward(
    activation2.output,
    y_true
)

print("\nCategorical Cross Entropy Loss:\n")
print(loss)

Dense Layer Output:

[[-1.49964952 -3.23687267 -3.26467943 -2.70174146  0.68145913]
 [-3.83174229 -5.16301966 -4.90862751 -3.43350315 -0.0229187 ]
 [-5.1160531  -6.91232204 -7.17434788 -3.97046471  0.07079607]]

ReLU Output:

[[0.         0.         0.         0.         0.68145913]
 [0.         0.         0.         0.         0.        ]
 [0.         0.         0.         0.         0.07079607]]

Second Dense Layer Output:

[[2.4068675  0.92467106]
 [1.         1.        ]
 [1.14615799 0.99217416]]

Sigmoid Output:

[[0.91734949 0.71599291]
 [0.73105858 0.73105858]
 [0.75880846 0.72951714]]

Categorical Cross Entropy Loss:

0.2383002848706234
