<a href="https://colab.research.google.com/github/tarannump096-cpu/Deep-Learning/blob/main/Deep_Learning6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
def sigmoid(x):
    return 1/1+np.exp(-x)

In [2]:
import numpy as np
def contructing_layer(inputs,weights,bias):
    output=np.dot(weights,inputs)
    output=output+bias
    ans=sigmoid(output)

    return ans

In [3]:
inputs=np.array([3,4,5,6])
weights=np.array([[1,2,3,4],
                 [4,5,6,7],
                 [6,7,8,9]])
bias=np.array([1,1,2])
contructing_layer(inputs,weights,bias)

array([1., 1., 1.])

In [4]:
inputs=np.array([3,4,5,6])
weights=np.array([[1,2,3,4],
                 [4,5,6,7],
                 [6,7,8,9]])

In [5]:
np.dot(weights,inputs)

array([ 50, 104, 140])

In [6]:
def coding_layers_batch(inputs,weights,bias):
    output=np.dot(inputs,weights.T)
    output=output+bias
    return output

In [7]:
inputs=np.array([[1,2,3,4],
                  [4,5,6,7],
				  [2,3,6,7]])
weights=np.array([[1,2,3,4],
			     [4,5,6,7],
                 [6,7,8,9]])
bias=np.ones((3,3))
coding_layers_batch(inputs,weights,bias)

array([[ 31.,  61.,  81.],
       [ 61., 127., 171.],
       [ 55., 109., 145.]])

In [8]:
inputs=np.array([[1,2,3,4],
                  [4,5,6,7],
				  [2,3,6,7]])
weights=np.array([[1,2,3,4],
			     [4,5,6,7],
                 [6,7,8,9]])

In [9]:
np.dot(inputs,weights.T)

array([[ 30,  60,  80],
       [ 60, 126, 170],
       [ 54, 108, 144]])

In [10]:
def coding_two_layers(inputs,weights_layer1,weights_layer2,bias_layer1,bias_layer2):
    o1=np.dot(weights_layer1,inputs)
    o1=o1+bias_layer1
    o2=np.dot(weights_layer2.T,o1)
    o2=o2+bias_layer2
    return o2

In [11]:
inputs=np.array([3,4,5,6])
weights_layer1=np.array([[1,2,3,4],
                         [4,5,6,7],
                         [6,7,8,9]])
weights_layer2=np.array([[1,2],
                        [1,3],
                        [1,1]])

bias_layer1=np.array([1,1,2])
bias_layer2=np.array([2,3])
coding_two_layers(inputs,weights_layer1,weights_layer2,bias_layer1,bias_layer2)

array([300, 562])

In [12]:
import sympy as sp

In [13]:
yi=sp.symbols("yi")
w1=sp.symbols("w1")
x=sp.symbols("x")
f=(yi-(w1*x))**2

In [14]:
sp.diff(f,w1)

-2*x*(-w1*x + yi)