<a href="https://colab.research.google.com/github/tarannump096-cpu/Deep-Learning/blob/main/Forward_%26_Backward_Propagation_%2C_Vanishing_Gradient.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ✍ Code for 3 weights:-



In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [ ]:
def sigmoid(x):
    return 1/np.exp(-x)

In [ ]:
def diff_sigmoid(x):
    return x*(1-x)

In [ ]:
def vanishing_gradient(w1,w2,w3,x,yactual,b,lr):
    #forward propagation
    o11=sigmoid((np.dot(w1,x))+b)
    o21=sigmoid((np.dot(w2,o11))+b)
    o31=sigmoid((np.dot(w3,o21))+b)

    #backward propagation
    # Calculate delta for the output layer
    delta_o31 = (np.array(yactual) - o31) * diff_sigmoid(o31)

    # Update weight w3
    grad_w3 = np.dot(delta_o31, o21.T)
    w3 = w3 + lr * grad_w3

    # Backpropagate delta to the second hidden layer
    # Note: This is a simplified propagation, assuming element-wise for (1,1) arrays
    # A more rigorous backprop would involve np.dot(w3.T, delta_o31)
    delta_o21 = delta_o31 * diff_sigmoid(o21)

    # Update weight w2
    grad_w2 = np.dot(delta_o21, o11.T)
    w2 = w2 + lr * grad_w2

    # Backpropagate delta to the first hidden layer
    # Similar simplification as above
    delta_o11 = delta_o21 * diff_sigmoid(o11)

    # Update weight w1
    grad_w1 = np.dot(delta_o11, np.array(x).T)
    w1 = w1 + lr * grad_w1

    return w1, w2, w3, o31

In [ ]:
w1=np.random.randn(1,1)
w2=np.random.randn(1,1)
w3=np.random.randn(1,1)
x=[[2.3]]
yactual=[[1]]
b1=b2=b3=1
learning_rate=0.01
vanishing_gradient(w1,w2,w3,x,yactual,b1,learning_rate)

(array([[112.48125407]]),
 array([[-8.02676469]]),
 array([[0.41310615]]),
 array([[2.88398025]]))

In [ ]:
np.dot(x,w1)

array([[0.95048887]])

In [ ]:
np.dot(w1,x)

array([[0.95048887]])

In [ ]:
# -------- Training Loop --------
for i in range(1000):
    w1, w2, w3, output = vanishing_gradient(w1, w2, w3, x, yactual, b1, learning_rate)

print("Final Output:", output)

Final Output: [[2.71828183]]


/tmp/ipykernel_2735/1333215068.py:2: RuntimeWarning: overflow encountered in exp
  return 1/np.exp(-x)


➰➰➰➰➰➰➰➰➰➰➰➰➰➰➰➰➰➰➰➰➰➰➰➰➰➰➰➰➰➰➰➰➰➰➰➰➰➰➰➰➰➰➰➰➰➰➰➰➰➰➰➰➰➰➰➰➰➰➰➰➰➰➰➰➰➰➰➰➰➰➰➰➰➰➰

# ✍ Code for tanh:-

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [ ]:
def tanh(x):
    return (np.exp(x) - np.exp(-x)) / (np.exp(x) + np.exp(-x))

In [ ]:
def diff_tanh(x):
    return 1-np.tanh(x)**2

In [ ]:
from sympy import symbols, tanh, diff

def solving_vanishing_gradient_problem(x_val, w1_val, w2_val, w3_val, b_val, yactual_val):
    # Define symbolic variables for SymPy
    x_sym, w1_sym, w2_sym, w3_sym, b_sym, yactual_sym = symbols('x w1 w2 w3 b yactual')

    # Forward propagation using symbolic operations
    # Assuming scalar operations as implied by np.random.randn(1,1) and x=[[2.5]]
    # If matrix operations are intended, sympy.Matrix should be used with appropriate dimensions.
    o11_sym = tanh((x_sym * w1_sym) + b_sym)
    o21_sym = tanh((o11_sym * w2_sym) + b_sym)
    o31_sym = tanh((o21_sym * w3_sym) + b_sym)

    yi_hat_sym = tanh(o31_sym)
    loss_sym = (yactual_sym - yi_hat_sym)**2

    # Backpropagation - calculate partial derivatives symbolically
    dL_dw1_sym = diff(loss_sym, w1_sym)
    dL_dw2_sym = diff(loss_sym, w2_sym)
    dL_dw3_sym = diff(loss_sym, w3_sym)

    # Prepare a dictionary for substituting numerical values into the symbolic expressions
    subs_dict = {
        x_sym: x_val[0][0] if isinstance(x_val, list) else x_val,
        w1_sym: w1_val[0][0] if isinstance(w1_val, (type(None), np.ndarray)) else w1_val,
        w2_sym: w2_val[0][0] if isinstance(w2_val, (type(None), np.ndarray)) else w2_val,
        w3_sym: w3_val[0][0] if isinstance(w3_val, (type(None), np.ndarray)) else w3_val,
        b_sym: b_val,
        yactual_sym: yactual_val
    }

    # -----------------------
    # Print results (both symbolic and numerical)
    # -----------------------
    print("Loss function (symbolic):\n", loss_sym)
    print("\nLoss function (numerical):\n", loss_sym.subs(subs_dict))
    print("\nGradient w.r.t w1 (symbolic):\n", dL_dw1_sym)
    print("\nGradient w.r.t w1 (numerical):\n", dL_dw1_sym.subs(subs_dict))
    print("\nGradient w.r.t w2 (symbolic):\n", dL_dw2_sym)
    print("\nGradient w.r.t w2 (numerical):\n", dL_dw2_sym.subs(subs_dict))
    print("\nGradient w.r.t w3 (symbolic):\n", dL_dw3_sym)
    print("\nGradient w.r.t w3 (numerical):\n", dL_dw3_sym.subs(subs_dict))

    return dL_dw1_sym, dL_dw2_sym, dL_dw3_sym

In [ ]:
import numpy as np
x=[[2.5]]
w1=np.random.randn(1,1)
w2=np.random.randn(1,1)
w3=np.random.randn(1,1)
b1=b2=b3=1
lr=0.01
y_actual=1
solving_vanishing_gradient_problem(x,w1,w2,w3,b1,y_actual)

Loss function (symbolic):
 (yactual - tanh(tanh(b + w3*tanh(b + w2*tanh(b + w1*x)))))**2

Loss function (numerical):
 0.654990767591402

Gradient w.r.t w1 (symbolic):
 -2*w2*w3*x*(1 - tanh(b + w1*x)**2)*(1 - tanh(b + w2*tanh(b + w1*x))**2)*(1 - tanh(b + w3*tanh(b + w2*tanh(b + w1*x)))**2)*(1 - tanh(tanh(b + w3*tanh(b + w2*tanh(b + w1*x))))**2)*(yactual - tanh(tanh(b + w3*tanh(b + w2*tanh(b + w1*x)))))

Gradient w.r.t w1 (numerical):
 3.93072443330681e-5

Gradient w.r.t w2 (symbolic):
 -2*w3*(1 - tanh(b + w2*tanh(b + w1*x))**2)*(1 - tanh(b + w3*tanh(b + w2*tanh(b + w1*x)))**2)*(1 - tanh(tanh(b + w3*tanh(b + w2*tanh(b + w1*x))))**2)*(yactual - tanh(tanh(b + w3*tanh(b + w2*tanh(b + w1*x)))))*tanh(b + w1*x)

Gradient w.r.t w2 (numerical):
 0.546138804268960

Gradient w.r.t w3 (symbolic):
 -2*(1 - tanh(b + w3*tanh(b + w2*tanh(b + w1*x)))**2)*(1 - tanh(tanh(b + w3*tanh(b + w2*tanh(b + w1*x))))**2)*(yactual - tanh(tanh(b + w3*tanh(b + w2*tanh(b + w1*x)))))*tanh(b + w2*tanh(b + w1*x))

Gradien

(-2*w2*w3*x*(1 - tanh(b + w1*x)**2)*(1 - tanh(b + w2*tanh(b + w1*x))**2)*(1 - tanh(b + w3*tanh(b + w2*tanh(b + w1*x)))**2)*(1 - tanh(tanh(b + w3*tanh(b + w2*tanh(b + w1*x))))**2)*(yactual - tanh(tanh(b + w3*tanh(b + w2*tanh(b + w1*x))))),
 -2*w3*(1 - tanh(b + w2*tanh(b + w1*x))**2)*(1 - tanh(b + w3*tanh(b + w2*tanh(b + w1*x)))**2)*(1 - tanh(tanh(b + w3*tanh(b + w2*tanh(b + w1*x))))**2)*(yactual - tanh(tanh(b + w3*tanh(b + w2*tanh(b + w1*x)))))*tanh(b + w1*x),
 -2*(1 - tanh(b + w3*tanh(b + w2*tanh(b + w1*x)))**2)*(1 - tanh(tanh(b + w3*tanh(b + w2*tanh(b + w1*x))))**2)*(yactual - tanh(tanh(b + w3*tanh(b + w2*tanh(b + w1*x)))))*tanh(b + w2*tanh(b + w1*x)))

🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠🧠

# ✍ Code for ReLu:-

In [ ]:
import numpy as np

In [ ]:
def ReLu(x):
  return np.maximum(0,x)

In [ ]:
def forward_propagatiob(x,w,b,yi):
    r=x*w+b
    yi_hat=ReLu(r)
    return yi_hat,yi,w,x

In [ ]:
def diff_ReLu(x):
  if x>0:
    return 1
  elif x<0:
    return 0


In [ ]:
def Backpropogation(yi_hat,yi,w,x):
    lr=0.01
    Loss=(yi-yi_hat)**2
    d_loss_yi_hat=-2*(yi-yi_hat)
    d_yi_hat_w=x
    r1=diff_ReLu(d_loss_yi_hat)
    r2=diff_ReLu(x)
    d_loss_w=r1*r2
    w_new=w-lr*d_loss_w
    return w,w_new

In [ ]:
x=2.2
w=0.8
yi=1
b=1
yi_hat,yi,w,x=forward_propagatiob(x,w,b,yi)

In [ ]:
w_old,w_new=Backpropogation(yi_hat,yi,w,x)

In [ ]:
w_old

0.8

In [ ]:
w_new

0.79

⚓⚓⚓⚓⚓⚓⚓⚓⚓⚓⚓⚓⚓⚓⚓⚓⚓⚓⚓⚓⚓⚓⚓⚓⚓⚓⚓⚓⚓⚓⚓⚓⚓⚓⚓⚓⚓⚓⚓⚓⚓⚓⚓⚓⚓⚓⚓⚓⚓⚓⚓⚓⚓⚓⚓⚓⚓⚓⚓⚓⚓⚓⚓⚓⚓⚓⚓⚓⚓⚓⚓⚓⚓⚓

# ✍ Or Code for 3 weights:-

In [ ]:
import numpy as np

In [ ]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

In [ ]:
def diff_sigmoid(x):
    return x*(1-x)

In [ ]:
def vanishing_gradient(w1,w2,w3,x,yactual,b,lr):
    #Forward Propagation
    o11=sigmoid((np.dot(w1,x))+b)
    o21=sigmoid((np.dot(w2,o11))+b)
    o31=sigmoid((np.dot(w3,o21))+b)

    yi_hat = o31

    # Error
    Loss = yactual - yi_hat

    # Backward Propagation

    # Output layer gradient
    d_output = Loss * diff_sigmoid(yi_hat)

    # Hidden layer 2 gradient
    d_hidden2 = np.dot(w3.T, d_output) * diff_sigmoid(o21)

    # Hidden layer 1 gradient
    d_hidden1 = np.dot(w2.T, d_hidden2) * diff_sigmoid(o11)

    # Update weights
    w3 += lr * np.outer(d_output, o21)
    w2 += lr * np.outer(d_hidden2, o11)
    w1 += lr * np.outer(d_hidden1, x)

    return w1, w2, w3, Loss


In [ ]:
# Example initialization
w1 = np.random.randn(4, 3)   # 4 neurons, 3 input features
w2 = np.random.randn(4, 4)   # 4 neurons
w3 = np.random.randn(1, 4)   # output layer

b = 0.1
lr = 0.01

In [ ]:
x = np.array([[2.5], [1.0], [0.5]]) # Example input, now with 3 features
yactual = np.array([[1]]) # Example target output, ensuring it's a numpy array

epochs = 1000

for i in range(epochs):
    w1, w2, w3, Loss = vanishing_gradient(w1, w2, w3, x, yactual, b, lr)

    if i % 100 == 0:
        print(f"Epoch {i}, Loss: {np.mean(np.abs(Loss))}")

Epoch 0, Loss: 0.5959037392389408
Epoch 100, Loss: 0.5570742263390268
Epoch 200, Loss: 0.5200576330373303
Epoch 300, Loss: 0.48538105903928985
Epoch 400, Loss: 0.4533132602637916
Epoch 500, Loss: 0.4239292822878391
Epoch 600, Loss: 0.397173266627033
Epoch 700, Loss: 0.37290863329703716
Epoch 800, Loss: 0.3509544457009184
Epoch 900, Loss: 0.3311102966777555


In [ ]:
def predict(w1, w2, w3, x, b):
    o11 = sigmoid((np.dot(w1, x)) + b)
    o21 = sigmoid((np.dot(w2, o11)) + b)
    o31 = sigmoid((np.dot(w3, o21)) + b)
    return o31

output = predict(w1, w2, w3, x, b)
print("Final Output:", output)

Final Output: [[0.68682741]]


⏰⏰⏰⏰⏰⏰⏰⏰⏰⏰⏰⏰⏰⏰⏰⏰⏰⏰⏰⏰⏰⏰⏰⏰⏰⏰⏰⏰⏰⏰⏰⏰⏰⏰⏰⏰⏰⏰⏰⏰⏰⏰⏰⏰⏰⏰⏰⏰⏰⏰⏰⏰⏰⏰⏰⏰⏰⏰⏰⏰⏰⏰⏰⏰⏰⏰⏰⏰⏰⏰⏰

# 💎Code for 3 weights:-

In [ ]:
import numpy as np

In [ ]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

In [ ]:
def vanishing_gradient(w1,w2,w3,x,yactual,b,lr):
    #Forward Propagation
    o11=sigmoid((np.dot(w1,x))+b)
    o21=sigmoid((np.dot(w2,o11))+b)
    o31=sigmoid((np.dot(w3,o21))+b)


In [ ]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_derivative(x):
    # Derivative of sigmoid where x is the output of the sigmoid function
    return x * (1 - x)

def vanishing_gradient(w1, w2, w3, x, yactual, b, lr):
    # Forward Propagation
    # Hidden layers
    # Assuming x is (input_features, 1) column vector
    # w1 is (h1_neurons, input_features)
    h1 = sigmoid(np.dot(w1, x) + b)
    # w2 is (h2_neurons, h1_neurons)
    h2 = sigmoid(np.dot(w2, h1) + b)

    # Output layer
    # w3 is (output_neurons, h2_neurons)
    y_pred = sigmoid(np.dot(w3, h2) + b)

    # --- Calculate Loss (Mean Squared Error) ---
    loss = 0.5 * (yactual - y_pred)**2

    # --- Backpropagation (Vanishing Gradient Demonstration) ---
    # 1. Gradient at Output layer (dy)
    # Error * derivative of sigmoid
    error = y_pred - yactual
    d_output = error * sigmoid_derivative(y_pred)

    # 2. Gradient at Hidden layer 2 (d_h2)
    # d_output is (output_neurons, 1), w3.T is (h2_neurons, output_neurons)
    d_h2 = np.dot(w3.T, d_output) * sigmoid_derivative(h2)

    # 3. Gradient at Hidden layer 1 (d_h1)
    # d_h2 is (h2_neurons, 1), w2.T is (h1_neurons, h2_neurons)
    d_h1 = np.dot(w2.T, d_h2) * sigmoid_derivative(h1)

    # --- Update Weights (Gradient Descent) ---
    # d_output is (output_neurons, 1), h2.T is (h2_neurons, 1) -> outer product (h2_neurons, output_neurons)
    w3 -= lr * np.dot(d_output, h2.T) # Changed order for outer product equivalent
    # d_h2 is (h2_neurons, 1), h1.T is (h1_neurons, 1) -> outer product (h1_neurons, h2_neurons)
    w2 -= lr * np.dot(d_h2, h1.T) # Changed order
    # d_h1 is (h1_neurons, 1), x.T is (1, input_features) -> outer product (h1_neurons, input_features)
    w1 -= lr * np.dot(d_h1, x.T) # Changed order

    return y_pred, loss, d_h1 # Returning early gradient to show it's small

# --- Example Usage ---
# Initialize weights with values that encourage saturation
np.random.seed(42)
# x: (input_features, 1) for consistency with np.dot(W, X)
x = np.random.randn(2, 1) # 2 input features
# w1: (h1_neurons, input_features)
w1 = np.random.randn(2, 2) * 5 # 2 neurons in h1, 2 input features
# w2: (h2_neurons, h1_neurons)
w2 = np.random.randn(2, 2) * 5 # 2 neurons in h2, 2 neurons in h1
# w3: (output_neurons, h2_neurons)
w3 = np.random.randn(1, 2) * 5 # 1 output neuron, 2 neurons in h2
b = 1.0 # Scalar bias for simplicity, will broadcast
y = np.array([[1.0]]) # Target output
lr = 0.1

# Run for one step
prediction, loss, early_grad = vanishing_gradient(w1, w2, w3, x, y, b, lr)

print(f"Prediction: {prediction}")
print(f"Loss: {loss}")
print(f"Gradient at early layer (should be very small): {early_grad}")


Prediction: [[0.05097096]]
Loss: [[0.45032806]]
Gradient at early layer (should be very small): [[-0.00771571]
 [ 0.01427181]]


# 💈💈💈💈💈💈💈💈💈💈💈💈💈💈💈💈💈💈💈💈💈💈💈💈💈💈💈💈💈💈💈💈💈💈💈💈💈💈💈💈💈💈💈💈💈💈💈💈💈💈💈💈💈💈💈💈💈💈💈💈💈💈💈💈💈💈💈💈💈💈💈💈💈💈💈💈💈💈💈💈💈💈💈💈💈💈💈💈💈💈💈💈💈💈💈💈💈💈💈💈💈💈💈💈💈💈💈💈💈💈💈💈💈💈💈💈💈💈💈💈💈💈💈

# ⌛Leaky Relu Code:

In [ ]:
import numpy as np

In [ ]:
def leaky_relu(inputs, alpha=0.01):
    # Returns x if x > 0, else alpha * x
    return [x if x > 0 else alpha * x for x in inputs]

data = [-3.0, -1.0, 0.0, 2.0]
result = leaky_relu(data)
print(result)

[-0.03, -0.01, 0.0, 2.0]
